.DEFAULT_GOAL = help

CHAT := ../tools/siflow_chat Qwen/Qwen2-72B-Instruct 
JSON := python3 ../tools/jsond.py

_DIR_ := ./out
$(shell mkdir -p $(_DIR_))

## 初始定义
define MESSAGES_INIT
[
	{"role": "system", "content": "你现在是一名富有经验的英语专家，擅长中英翻译，英语写作等工作。"}
]
endef
export MESSAGES_INIT

## 定义英翻中的提示词
define TRANS_ZH
请将下面这段英文翻译为中文，果遇到的输入不是英文，请输出：'请输入中文'。输出格式使用 JSON 格式，结果放在'result'字段。
比如：
'''
[输入]： Hello world
[输出]： {'result': '你好，世界'}
'''

endef
export TRANS_ZH

## 定义中翻英的提示词
define TRANS_ENG
请将下面这段中文翻译为英语，果遇到的输入不是中文，请输出：'Please input Chinese'。输出格式使用 JSON 格式，结果放在'result'字段。
比如：
'''
[输入]： 你好，世界
[输出]： {'result': 'hello world'}
'''


endef
export TRANS_ENG

help:
	@echo "请使用下面的命令，进行操作:"
	@echo "zh: 英翻中"
	@echo "eng: 中翻英"
	@echo "fix_gram: 修正英语语法错误"
	@echo "make_pro: 用专业的风格改进英语"
	@echo "make_simp: 用简单的语法修改英语"

.PHONY: zh
.ONESHELL: zh
zh:
	@echo "请输出你要翻译的英文，回车结束。"
	read SOURCE_WORDS
	if [ -z "$${SOURCE_WORDS}" ]; then echo "输入错误"; exit ; fi
	echo "$$MESSAGES_INIT" > $(_DIR_)/h.json
	echo "$$TRANS_ZH" $$SOURCE_WORDS > $(_DIR_)/u.txt
	$(CHAT) $(_DIR_)/h.json $(_DIR_)/u.txt $(_DIR_)/a.txt $(_DIR_)/h.json $(_DIR_)/first.json
	$(JSON) $(_DIR_)/first.json '["result"]' > $(_DIR_)/v.txt
	cat $(_DIR_)/v.txt

.PHONY: eng
.ONESHELL: eng
eng:
	@echo "Please input Chinese ends with enter."
	read SOURCE_WORDS
	if [ -z "$${SOURCE_WORDS}" ]; then echo "Input Error"; exit ; fi
	echo "$$MESSAGES_INIT" > $(_DIR_)/h.json
	echo "$$TRANS_ENG" $$SOURCE_WORDS > $(_DIR_)/u.txt
	$(CHAT) $(_DIR_)/h.json $(_DIR_)/u.txt $(_DIR_)/a.txt $(_DIR_)/h.json $(_DIR_)/first.json
	$(JSON) $(_DIR_)/first.json '["result"]' > $(_DIR_)/v.txt
	cat $(_DIR_)/v.txt

