.DEFAULT_GOAL = QA

CHAT := ../tools/siflow_chat Qwen/Qwen2-72B-Instruct 
JSON := python3 ../tools/jsond.py

_DIR_ := ./out
$(shell mkdir -p $(_DIR_))

## 初始定义
define MESSAGES_INIT
[
	{ "role": "system", 
	  "content": "你现在是一名富有经验的项目管理专家，现在需要完成一份文档填写，填写的内容是关于人工智能相关开发的工作量和难点说明。"
	}
]
endef
export MESSAGES_INIT

## 背景定义
define CONTEXT

一个相关的填写例子如下：

'''
输入：
[项目建设内容]
多机器人集成：与不同厂商的机器人设备对接，需处理多样化的通信协议和控制逻辑，增加调试难度和周期。

项目经理：规划项目，管理进度，协调资源，确保项目按时交付。
前端开发：设计并实现用户界面，提升用户体验。
后端开发：处理系统逻辑、数据库和接口开发，确保系统稳定运行。
移动端开发：专注于App功能开发，优化移动端体验。
三维可视化工程师：负责三维数字孪生水厂系统的设计与实现，确保空间地图的精确构建和实时更新。
三维模型工程师：负责三维数字孪生水厂四足机器人、地图、传感器的建模设计，以满足在三维水厂中的展现与交互。
测试工程师：负责系统测试，确保功能正确、稳定可靠。

输出:
[项目 工作描述/难点描述]

参与角色：产品经理(1.5名)、1名项目经理(0.5名)
    时间预估：5人月
    主要工作量：
        编写需求规格说明书：产品经理根据调研、讨论结果，详细撰写需求规格说明书，包括功能描述、业务流程图、输入输出示例等，确保需求的准确性和可追溯性。
      处理异常情况：需求变更：若在需求分析过程中发现遗漏或需求变更，需及时召开变更评审会议，更新需求规格说明书和项目计划。

'''

接下来请根据相关的工作描述，输出 工作描述/难点描述。

endef
export CONTEXT 

.PHONY: QA
.ONESHELL: QA
QA: 
	@echo "客户您好，请输入 建设内容："
	read -p "=> " QUESTION
	if [ -z "$${QUESTION}" ]; then echo "谢谢！"; exit ; fi
	echo "$$MESSAGES_INIT" > $(_DIR_)/h.json
	echo "$$CONTEXT" "建设内容：" $$QUESTION > $(_DIR_)/u.txt
	$(CHAT) $(_DIR_)/h.json $(_DIR_)/u.txt $(_DIR_)/a.txt $(_DIR_)/h.json
	printf "\n--------工作量和难点如下----------\n"
	cat $(_DIR_)/a.txt
	printf "\n"
	@$(MAKE) -f Makefile.customer  QA_CONT

.PHONY: QA_CONT
.ONESHELL: QA_CONT
QA_CONT: 
	@read -p "=> " QUESTION
	if [ -z "$${QUESTION}" ]; then echo "谢谢！"; exit ; fi
	$(CHAT) $(_DIR_)/h.json $(_DIR_)/u.txt $(_DIR_)/a.txt $(_DIR_)/h.json
	printf "\n--------工作量和难点如下----------\n"
	cat $(_DIR_)/a.txt
	printf "\n"
	@$(MAKE) -f Makefile.customer  QA_CONT


.PHONY: clean
clean:
	rm -rf $(_DIR_)
